[tool.poetry]
name = "async-vk-bots"
version = "0.1.5"
description = "Library for creating asynchronous vk bots"
authors = ["mihett05 <mihett05@yandex.ru>"]
url = "https://github.com/mihett05/async-vk-bots"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
