[tool.poetry]
name = "owclient"
version = "0.1.0"
description = ""
authors = ["Ferran Comabella <ferran@fccma.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pyownet = "~0.10.0"

[tool.poetry.dev-dependencies]
pytest = "~5.4.1"
flake8 = "~3.7.9"
pytest-mock = "~2.0.0"
coverage = "~5.0.3"
pytest-cov = "~2.8.1"
mypy = "~0.761"
isort = "~4.3.21"
yapf = "~0.29.0"
rope = "~0.16.0"
sphinx = "^2.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
