[tool.poetry]
name = "woops"
version = "0.2.1"
description = "Handle and manage Python errors with ease"
authors = ["SÃ©bastien Eustace <sebastien@eustace.io>"]
license = "MIT"
readme = "README.md"

homepage = "https://github.com/sdispater/woops"
repository = "https://github.com/sdispater/woops"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
black = "^19.10b0"
pytest-cov = "^2.8.1"
pre-commit = "^1.20.0"

[build-system]
requires = ["poetry-core>=1.0.0a3"]
build-backend = "poetry_core.masonry.api"


[tool.isort]
line_length = 88
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
use_parentheses = true
not_skip = "__init__.py"
skip_glob = ["*/setup.py"]
filter_files = true

known_first_party = "woops"
known_third_party = ["pytest"]
