email:
  biz:
    subject: é‚®ä»¶æµ‹è¯•
    receivers: [yuanjie@xiaomi.com,]
    msg: æµ‹è¯•ä¿¡æ¯,
    emoji: ğŸ¥°
    msg_prefix: ğŸ‘
    msg_suffix: ğŸ‘
    date: '20200202'
    msg_fn: 'lambda x: x'


  push:
    subject: ''
    receivers: ''
    msg_prefix: ''
    msg_suffix: ''
